#!/usr/bin/env python3
#-*- coding: utf-8 -*-
## Created on 2024-01-29 at 11:33:43 CET by David Gaspard <david.gaspard@espci.fr>
## Python script to automatically generate a TikZ file from a template in order to plot the results of the "task_tprofile" operation of the Ebsolve program.
## USAGE : ./tikz/tprofile_group.py "FILENAME_TPROFILE" "TITLE"
## FILENAME_TPROFILE  = Data file generated by RecurGreen containing the transmission profiles (Input file, CSV format).
## TITLE              = LaTeX title of the TikZ figure (Input string).
import sys
import os
import compile_tikz

TEMPLATE_TIKZ = "tikz/tprofile_group.tikz"   ## TikZ template for the "task_distrib" operation of the Ebsolve program.

def main(args):
    """
    Main function of the script.
    """
    ## 1. Check for possible errors:
    nargs_expc = 2  ## Expected number of arguments
    if (len(args) - 1 != nargs_expc):
        print("[ERROR] Invalid arguments, expected " + str(nargs_expc) + " arguments...")
        print("[USAGE] " + args[0] + " file.csv 'title' ")
        return 1
    if (not os.path.isfile(TEMPLATE_TIKZ)):
        print("[ERROR] TikZ template not found: '" + TEMPLATE_TIKZ + "'...")
        return 1
    
    
    ## 2. Deduce the file path of the output TikZ file from the data file "*.csv":
    filename_tikz = os.path.join(os.path.dirname(args[1]), os.path.basename(args[1]).replace(".csv", ".tikz"))
    
    ## 3. Check if the file can be overwritten if it already exists:
    if (not compile_tikz.can_overwrite(filename_tikz)):
        return 1
    
    ## 4. Prepare the substitution dictionary:
    dic = {## Substitution dictionary:
        ##"filename_distrib": os.path.basename(args[1]),
        "title": args[2]
    }
    
    ## 5. Creates the new TikZ file from the template:
    tpl_tikz = open(TEMPLATE_TIKZ, 'r').read()
    code_tikz = tpl_tikz % dic  ## Achieve the substitution.
    code_tikz = compile_tikz.get_header_comment(args[1], '%') + code_tikz  ## Insert the CSV header for information.
    open(filename_tikz, 'w').write(code_tikz)  ## Write the code to the new TikZ file.
    
    ## 6. Compile the TikZ file in PDF using the global LaTeX preamble "preamble.tex":
    compile_tikz.compile_tikz(filename_tikz)
    
    return 0

if (__name__ == '__main__'):
    exit(main(sys.argv))
